NUM_OF_HYPHENS = 50
RESOURCES_DIR = 'resources'
RESOURCES_DATASETS_DIR = RESOURCES_DIR + '/datasets'
RESOURCES_RESULTS_DIR = RESOURCES_DIR + '/results'
RESOURCES_MODELS_DIR = RESOURCES_DIR + '/models'



