SERVICE_NAME = "phd-defense"
SERVICE_NAME_SNAKED = SERVICE_NAME.replace('-', '_')

LOCAL_OUTPUTS_MAIN_DIR = 'resources'
LOCAL_DATASETS_DIR = LOCAL_OUTPUTS_MAIN_DIR + '/datasets'
LOCAL_RESULTS_DIR = LOCAL_OUTPUTS_MAIN_DIR + '/results'
LOCAL_MODELS_DIR = LOCAL_OUTPUTS_MAIN_DIR + '/models'

NUM_OF_HYPHENS = 50
STR_PARAM_SEPARATOR = '|'
